# Copyright 2024 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build for a Wireless Choctopus44'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["choctopus44"]'
      kconfig: '["CONFIG_ZMK_POINTING=y"]'
